# PUSH IMAGE TO DOCKER HUB  
sudo: required
services:
  - docker

before_install:
  - docker build -t nk/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true nk/react-test npm test

after_success:
  - docker build -t nk/multi-client ./client
  - docker build -t nk/multi-nginx ./nginx
  - docker build -t nk/multi-server ./server
  - docker build -t nk/multi-worker ./worker
# Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin docker.io
# Take those images and push them to docker hub
  - docker push nk/multi-client
  - docker push nk/multi-nginx
  - docker push nk/multi-server
  - docker push nk/multi-worker
